import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  organizations: defineTable({
    name: v.string(),
    slug: v.string(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),
  memberships: defineTable({
    organizationId: v.id("organizations"),
    identitySubject: v.string(),
    role: v.union(v.literal("owner"), v.literal("admin"), v.literal("member"), v.literal("viewer")),
    status: v.union(v.literal("active"), v.literal("suspended")),
    createdAt: v.number(),
  }).index("by_organization", ["organizationId"])
    .index("by_organization_subject", ["organizationId", "identitySubject"])
    .index("by_subject", ["identitySubject"]),
  tasks: defineTable({
    organizationId: v.id("organizations"),
    title: v.string(),
    kind: v.union(v.literal("coding"), v.literal("research"), v.literal("writing"), v.literal("operations")),
    status: v.union(v.literal("draft"), v.literal("quoted"), v.literal("awaiting_approval"), v.literal("running"), v.literal("completed"), v.literal("blocked"), v.literal("cancelled")),
    quality: v.union(v.literal("fast"), v.literal("balanced"), v.literal("expert")),
    maxRwf: v.int64(),
    spentRwf: v.int64(),
    reservedRwf: v.int64(),
    expectedOutput: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_status", ["status"]).index("by_organization", ["organizationId"]),
  taskQuotes: defineTable({
    taskId: v.id("tasks"),
    version: v.number(),
    estimateLowRwf: v.int64(),
    estimateHighRwf: v.int64(),
    maxRwf: v.int64(),
    confidence: v.union(v.literal("high"), v.literal("medium"), v.literal("low")),
    assumptions: v.array(v.string()),
    estimatorVersion: v.string(),
    createdAt: v.number(),
  }).index("by_task", ["taskId"]),
  paymentHolds: defineTable({
    taskId: v.id("tasks"),
    amountRwf: v.int64(),
    provider: v.literal("circuit_pay"),
    providerReference: v.optional(v.string()),
    status: v.union(v.literal("pending"), v.literal("authorized"), v.literal("captured"), v.literal("released"), v.literal("refunded")),
    idempotencyKey: v.string(),
    createdAt: v.number(),
  }).index("by_task", ["taskId"]).index("by_idempotency_key", ["idempotencyKey"]),
  taskEvents: defineTable({
    taskId: v.id("tasks"),
    type: v.string(),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_task", ["taskId"]),
  agentRuns: defineTable({
    taskId: v.id("tasks"),
    parentRunId: v.optional(v.id("agentRuns")),
    delegationDepth: v.optional(v.number()),
    kind: v.optional(v.union(v.literal("coding"), v.literal("research"), v.literal("writing"), v.literal("operations"))),
    role: v.union(v.literal("planner"), v.literal("coding"), v.literal("reviewer"), v.literal("research"), v.literal("operator")),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("awaiting_approval"), v.literal("blocked"), v.literal("completed"), v.literal("failed"), v.literal("cancelled"), v.literal("needs_configuration")),
    objective: v.string(),
    capabilityIds: v.optional(v.array(v.string())),
    maxParallelism: v.number(),
    createdAt: v.number(),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    cancelRequestedAt: v.optional(v.number()),
  }).index("by_task", ["taskId"]).index("by_status", ["status"]),
  agentSteps: defineTable({
    runId: v.id("agentRuns"),
    stepKey: v.string(),
    title: v.string(),
    role: v.union(v.literal("planner"), v.literal("coding"), v.literal("reviewer"), v.literal("research"), v.literal("operator")),
    status: v.union(v.literal("pending"), v.literal("ready"), v.literal("running"), v.literal("awaiting_approval"), v.literal("completed"), v.literal("failed"), v.literal("blocked"), v.literal("cancelled")),
    dependsOn: v.array(v.string()),
    requiresApproval: v.boolean(),
    sandboxTemplate: v.optional(v.union(v.literal("coding"), v.literal("browser"), v.literal("data"))),
    capabilityIds: v.optional(v.array(v.string())),
    approvalStatus: v.optional(v.union(v.literal("not_required"), v.literal("pending"), v.literal("approved"), v.literal("rejected"))),
    attempts: v.number(),
    claimedBy: v.optional(v.string()),
    claimedAt: v.optional(v.number()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    sandboxId: v.optional(v.string()),
    reservedRwf: v.optional(v.int64()),
    completedAt: v.optional(v.number()),
    summary: v.optional(v.string()),
    artifactReferences: v.optional(v.array(v.string())),
    createdAt: v.number(),
  }).index("by_run", ["runId"]).index("by_run_step_key", ["runId", "stepKey"]).index("by_status_lease", ["status", "leaseExpiresAt"]),
  agentArtifacts: defineTable({
    taskId: v.id("tasks"),
    runId: v.id("agentRuns"),
    stepId: v.id("agentSteps"),
    kind: v.union(v.literal("model_plan"), v.literal("command_log"), v.literal("patch"), v.literal("test_log"), v.literal("review_summary")),
    mediaType: v.string(),
    reference: v.string(),
    sha256: v.string(),
    byteLength: v.number(),
    createdAt: v.number(),
  }).index("by_task", ["taskId"]).index("by_run", ["runId"]).index("by_step", ["stepId"]).index("by_reference", ["reference"]),
  agentRunEvents: defineTable({
    runId: v.id("agentRuns"),
    type: v.string(),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_run", ["runId"]),
  approvals: defineTable({
    taskId: v.id("tasks"),
    runId: v.optional(v.id("agentRuns")),
    stepId: v.optional(v.id("agentSteps")),
    actionIntentId: v.optional(v.id("connectorActionIntents")),
    // "task_start" is the cost gate: a quoted task exists and is priced, but nothing is spent
    // until a person accepts the quote. Accepting it is what authorizes the payment hold.
    kind: v.union(v.literal("task_start"), v.literal("execute_step"), v.literal("budget_overage"), v.literal("merge"), v.literal("deploy"), v.literal("external_action")),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected"), v.literal("expired")),
    requestedRwf: v.optional(v.int64()),
    requestedAt: v.number(),
    decidedAt: v.optional(v.number()),
    decidedBy: v.optional(v.string()),
  }).index("by_task", ["taskId"]).index("by_status", ["status"]),
  usageLedger: defineTable({
    taskId: v.id("tasks"),
    runId: v.optional(v.id("agentRuns")),
    stepId: v.optional(v.id("agentSteps")),
    provider: v.string(),
    meter: v.string(),
    quantity: v.number(),
    amountRwf: v.int64(),
    providerReference: v.optional(v.string()),
    idempotencyKey: v.string(),
    createdAt: v.number(),
  }).index("by_task", ["taskId"]).index("by_idempotency_key", ["idempotencyKey"]),
  connectorConnections: defineTable({
    organizationId: v.id("organizations"),
    connectorId: v.string(),
    status: v.union(v.literal("pending"), v.literal("connected"), v.literal("degraded"), v.literal("revoked"), v.literal("expired")),
    permissions: v.array(v.union(v.literal("read"), v.literal("draft"), v.literal("execute"))),
    credentialReference: v.string(),
    externalAccountLabel: v.optional(v.string()),
    scopes: v.array(v.string()),
    connectedAt: v.number(),
    updatedAt: v.number(),
    expiresAt: v.optional(v.number()),
  }).index("by_organization", ["organizationId"])
    .index("by_organization_connector", ["organizationId", "connectorId"]),
  connectorActionIntents: defineTable({
    organizationId: v.id("organizations"),
    taskId: v.id("tasks"),
    runId: v.optional(v.id("agentRuns")),
    stepId: v.optional(v.id("agentSteps")),
    connectionId: v.id("connectorConnections"),
    connectorId: v.string(),
    actionId: v.string(),
    permission: v.union(v.literal("read"), v.literal("draft"), v.literal("execute")),
    risk: v.union(v.literal("read"), v.literal("write"), v.literal("send"), v.literal("control"), v.literal("purchase"), v.literal("delete")),
    status: v.union(v.literal("proposed"), v.literal("awaiting_approval"), v.literal("approved"), v.literal("executing"), v.literal("completed"), v.literal("failed"), v.literal("cancelled")),
    idempotencyKey: v.string(),
    inputSummary: v.string(),
    payloadReference: v.optional(v.string()),
    outputSummary: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organization", ["organizationId"])
    .index("by_task", ["taskId"])
    .index("by_status", ["status"])
    .index("by_idempotency_key", ["idempotencyKey"]),
  connectorEvents: defineTable({
    organizationId: v.id("organizations"),
    connectionId: v.optional(v.id("connectorConnections")),
    actionIntentId: v.optional(v.id("connectorActionIntents")),
    type: v.string(),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_organization", ["organizationId"])
    .index("by_connection", ["connectionId"])
    .index("by_action_intent", ["actionIntentId"]),
  agentSchedules: defineTable({
    organizationId: v.id("organizations"),
    title: v.string(),
    workflowTemplate: v.string(),
    cronExpression: v.string(),
    timezone: v.string(),
    status: v.union(v.literal("paused"), v.literal("active"), v.literal("disabled")),
    connectorIds: v.array(v.string()),
    /** Only meaningful for the "coding-task" template: the objective run on every occurrence. */
    objective: v.optional(v.string()),
    nextRunAt: v.optional(v.number()),
    claimedBy: v.optional(v.string()),
    claimExpiresAt: v.optional(v.number()),
    lastRunAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organization", ["organizationId"])
    .index("by_status_next_run", ["status", "nextRunAt"]),
  channelLinkAttempts: defineTable({
    organizationId: v.id("organizations"),
    identitySubject: v.string(),
    channel: v.union(v.literal("telegram")),
    codeHash: v.string(),
    expiresAt: v.number(),
    consumedAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_code_hash", ["codeHash"])
    .index("by_organization", ["organizationId"]),
  channelLinks: defineTable({
    organizationId: v.id("organizations"),
    channel: v.union(v.literal("telegram")),
    channelUserId: v.string(),
    status: v.union(v.literal("linked"), v.literal("revoked")),
    linkedAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organization", ["organizationId"])
    .index("by_channel_user", ["channel", "channelUserId"]),
  connectorVaultEntries: defineTable({
    organizationId: v.id("organizations"),
    kind: v.union(v.literal("oauth_tokens"), v.literal("oauth_pkce"), v.literal("action_payload")),
    algorithm: v.literal("aes-256-gcm"),
    keyVersion: v.number(),
    iv: v.string(),
    ciphertext: v.string(),
    authTag: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organization", ["organizationId"]),
  connectorOAuthStates: defineTable({
    organizationId: v.id("organizations"),
    identitySubject: v.string(),
    connectorId: v.string(),
    stateHash: v.string(),
    pkceReference: v.string(),
    redirectUri: v.string(),
    expiresAt: v.number(),
    consumedAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_state_hash", ["stateHash"])
    .index("by_organization", ["organizationId"]),
  calendarWatchChannels: defineTable({
    organizationId: v.id("organizations"),
    connectionId: v.id("connectorConnections"),
    channelId: v.string(),
    resourceId: v.string(),
    tokenHash: v.string(),
    status: v.union(v.literal("active"), v.literal("expired"), v.literal("stopped")),
    expiration: v.number(),
    lastMessageNumber: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_channel_id", ["channelId"])
    .index("by_connection", ["connectionId"])
    .index("by_expiration", ["status", "expiration"]),
  skills: defineTable({
    organizationId: v.id("organizations"),
    slug: v.string(),
    version: v.number(),
    title: v.string(),
    taskKind: v.union(v.literal("coding"), v.literal("research"), v.literal("writing"), v.literal("operations")),
    proceduralSummary: v.string(),
    sourceRunId: v.id("agentRuns"),
    sourceObjective: v.string(),
    status: v.union(v.literal("proposed"), v.literal("approved"), v.literal("rejected"), v.literal("retired")),
    createdAt: v.number(),
    updatedAt: v.number(),
    decidedBy: v.optional(v.string()),
    decidedAt: v.optional(v.number()),
  }).index("by_organization", ["organizationId"])
    .index("by_organization_status", ["organizationId", "status"])
    .index("by_organization_slug", ["organizationId", "slug"]),
  githubInstallAttempts: defineTable({
    organizationId: v.id("organizations"),
    identitySubject: v.string(),
    stateHash: v.string(),
    expiresAt: v.number(),
    consumedAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_state_hash", ["stateHash"])
    .index("by_organization", ["organizationId"]),
  githubInstallations: defineTable({
    organizationId: v.id("organizations"),
    installationId: v.string(),
    accountLogin: v.string(),
    accountType: v.union(v.literal("Organization"), v.literal("User")),
    repositorySelection: v.union(v.literal("all"), v.literal("selected")),
    allowedRepositories: v.array(v.string()),
    status: v.union(v.literal("connected"), v.literal("suspended"), v.literal("revoked")),
    connectedAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organization", ["organizationId"])
    .index("by_installation_id", ["installationId"]),
  terminalPresets: defineTable({
    organizationId: v.id("organizations"),
    contextKey: v.string(),
    presets: v.array(v.object({ label: v.string(), objective: v.string() })),
    generatedAt: v.number(),
  }).index("by_organization", ["organizationId"]),
  connectorScheduleRuns: defineTable({
    organizationId: v.id("organizations"),
    scheduleId: v.id("agentSchedules"),
    dueAt: v.number(),
    idempotencyKey: v.string(),
    status: v.union(v.literal("claimed"), v.literal("completed"), v.literal("failed")),
    claimedBy: v.string(),
    leaseExpiresAt: v.number(),
    attempts: v.number(),
    summary: v.optional(v.string()),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_schedule", ["scheduleId"])
    .index("by_idempotency_key", ["idempotencyKey"])
    .index("by_status_lease", ["status", "leaseExpiresAt"]),
});
